#!/bin/bash

set -e


if [ "$(git status -s)" != "" ]; then
   echo not clean git
   exit
fi

./build-w32.sh
./build-linux.sh
./build-doc.sh

SAVE_DIR=saved_builds

LATEST=$(git tag -l build\*|cut -c 6-|sort -n|tail -n 1)
NEXT=$((LATEST+1))

git tag -a "build${NEXT}" -m "tag generated by build script"

TIME=`date +"%Y-%m-%d_%H_%M_%S"`
NAME=${TIME}_nr_${NEXT}
DIR="build_${NAME}"

mkdir -p $SAVE_DIR/$DIR
cd $SAVE_DIR
cp ../build_w32/release/fysik1.exe  $DIR/fysik1_w32_${NAME}.exe
cp ../build_linux/fysik1 $DIR/fysik_$(arch)_${NAME}
cp ../build_doc/physicsengine.pdf $DIR

zip $DIR.zip -r $DIR

